# Generated by Django 3.2 on 2021-05-08 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscourse_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='favors',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resource',
            name='prefers',
            field=models.IntegerField(default=0),
        ),
    ]
