# Generated by Django 3.2 on 2021-05-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscourse_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='short_name',
            field=models.CharField(default='Course', max_length=10),
            preserve_default=False,
        ),
    ]
