# Generated by Django 3.2 on 2021-05-02 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscourse_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('heat', models.IntegerField()),
                ('image', models.BinaryField()),
                ('category', models.IntegerField()),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscourse_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('mate_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_id', models.IntegerField()),
                ('request_user', models.IntegerField()),
                ('accept_id', models.IntegerField()),
                ('establish_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_key', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('type', models.IntegerField()),
                ('content', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscourse_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='MateSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('progress', models.FloatField()),
                ('status', models.IntegerField()),
                ('mate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscourse_backend.mate')),
            ],
        ),
        migrations.CreateModel(
            name='CourseJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscourse_backend.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscourse_backend.user')),
            ],
        ),
    ]
