# Generated by Django 3.2 on 2021-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscourse_backend', '0002_auto_20210511_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='youremail@inscourse.com', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.CharField(default='快来编辑你的个性签名吧', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='workspace',
            field=models.CharField(default='inscourse university', max_length=40),
        ),
    ]
