# Generated by Django 3.2 on 2021-05-03 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscourse_backend', '0002_course_coursejoin_mate_mateschedule_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscourse_backend.course'),
        ),
        migrations.AlterField(
            model_name='mateschedule',
            name='progress',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='content',
            field=models.TextField(),
        ),
    ]
